package com.myspace.fraud_detection_example;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BasicDataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String transactionId;

	private Date date;

	public BasicDataObject() {
	}

	public java.lang.String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(java.lang.String transactionId) {
		this.transactionId = transactionId;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public BasicDataObject(java.lang.String transactionId, java.util.Date date) {
		this.transactionId = transactionId;
		this.date = date;
	}

}