package com.myspace.fraud_detection_example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BasicDataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String transactionId;

	private java.time.LocalDateTime transactionDateTime;

	private java.math.BigDecimal transactionAmount;

	private java.lang.String transactionLocation;

	public BasicDataObject() {
	}

	public java.lang.String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(java.lang.String transactionId) {
		this.transactionId = transactionId;
	}

	public java.time.LocalDateTime getTransactionDateTime() {
		return this.transactionDateTime;
	}

	public void setTransactionDateTime(
			java.time.LocalDateTime transactionDateTime) {
		this.transactionDateTime = transactionDateTime;
	}

	public java.math.BigDecimal getTransactionAmount() {
		return this.transactionAmount;
	}

	public void setTransactionAmount(java.math.BigDecimal transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	public java.lang.String getTransactionLocation() {
		return this.transactionLocation;
	}

	public void setTransactionLocation(java.lang.String transactionLocation) {
		this.transactionLocation = transactionLocation;
	}

	public BasicDataObject(java.lang.String transactionId,
			java.time.LocalDateTime transactionDateTime,
			java.math.BigDecimal transactionAmount,
			java.lang.String transactionLocation) {
		this.transactionId = transactionId;
		this.transactionDateTime = transactionDateTime;
		this.transactionAmount = transactionAmount;
		this.transactionLocation = transactionLocation;
	}

}