package com.myspace.fraud_detection_example;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("transactionId")
	private java.lang.Integer transactionId;
	@org.kie.api.definition.type.Label("transactionAmount")
	private java.math.BigDecimal transactionAmount;

	@org.kie.api.definition.type.Label("transactionDateTime")
	private java.util.Date transactionDateTime;

	@org.kie.api.definition.type.Label(value = "transactionLocation")
	private java.lang.String transactionLocation;

	public Transaction() {
	}

	public java.lang.Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(java.lang.Integer transactionId) {
		this.transactionId = transactionId;
	}

	public java.math.BigDecimal getTransactionAmount() {
		return this.transactionAmount;
	}

	public void setTransactionAmount(java.math.BigDecimal transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	public java.util.Date getTransactionDateTime() {
		return this.transactionDateTime;
	}

	public void setTransactionDateTime(java.util.Date transactionDateTime) {
		this.transactionDateTime = transactionDateTime;
	}

	public java.lang.String getTransactionLocation() {
		return this.transactionLocation;
	}

	public void setTransactionLocation(java.lang.String transactionLocation) {
		this.transactionLocation = transactionLocation;
	}

	public Transaction(java.lang.Integer transactionId,
			java.math.BigDecimal transactionAmount,
			java.util.Date transactionDateTime,
			java.lang.String transactionLocation) {
		this.transactionId = transactionId;
		this.transactionAmount = transactionAmount;
		this.transactionDateTime = transactionDateTime;
		this.transactionLocation = transactionLocation;
	}

}