package com.myspace.fraud_detection_example;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("transactionId")
	private java.lang.Integer transactionId;
	@org.kie.api.definition.type.Label("dateTime")
	private Date dateTime;
	@org.kie.api.definition.type.Label("location")
	private java.lang.String location;
	@org.kie.api.definition.type.Label("amount")
	private Integer amount;

	public Transaction() {
	}

	public java.lang.Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(java.lang.Integer transactionId) {
		this.transactionId = transactionId;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.util.Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(java.util.Date dateTime) {
		this.dateTime = dateTime;
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public Transaction(java.lang.Integer transactionId,
			java.util.Date dateTime, java.lang.String location,
			java.lang.Integer amount) {
		this.transactionId = transactionId;
		this.dateTime = dateTime;
		this.location = location;
		this.amount = amount;
	}

}